spring:
  datasource:
#    url: jdbc:h2:file:/Users/sriram/Workspace/HomeFinance/shf-account-service
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
        mode: embedded
        schema-locations: classpath:static/sql/import_schema_*.sql
        data-locations: classpath:static/sql/import_data_*.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    #    defer-datasource-initialization: true (used only when you want to use both hibernate and sql based initialization)
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    org.hibernate.SQL: trace