CREATE TABLE IF NOT EXISTS ACCOUNTS
(
  ID              			INT NOT NULL AUTO_INCREMENT,
  CARD_NUMBER            	VARCHAR(150) NOT NULL,
  CARD_HOLDER_NAME          VARCHAR(150) NOT NULL,
  BANK_NAME           		VARCHAR(150) NOT NULL,
  CARD_PROVIDER           	VARCHAR(150) NOT NULL,
  EXPIRY           			VARCHAR(150) NOT NULL,
  DOB           			DATE NOT NULL,
  CREATED_BY				VARCHAR(150),
  CREATED_ON				DATETIME,
  MODIFIED_BY		        VARCHAR(150),
  MODIFIED_ON  				DATETIME,
  PRIMARY KEY     (id)
);